# 练习题1


In [4]:
import numpy as np
arr = np.arange(1, 13).reshape(3, 4)
print(arr.ndim)
print(arr.shape)
print(arr.size)

2
(3, 4)
12


# 练习题2

In [5]:
import numpy as np

arr = np.array([1.5, 2.6, 3.7, 4.8])
print(arr)
print(arr.dtype.name)

arr_int = arr.astype(np.int32)
print(arr_int)
print(arr_int.dtype.name)

[1.5 2.6 3.7 4.8]
float64
[1 2 3 4]
int32


## 练习题3

In [6]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
sub_arr = arr[:2, 1:3]
print(sub_arr)

[[2 3]
 [6 7]]


## 练习题4

In [14]:
import numpy as np

arr = np.array([10,15,20,25,30,35])

# 花式索引
print(arr[[0, 2, 4]])

# 布尔索引
print(arr[arr > 20])

[10 20 30]
[25 30 35]


## 5

In [8]:
import numpy as np

arr_a = np.zeros((3, 4))
arr_b = np.array([1, 2, 3, 4])
result = arr_a + arr_b
print(result)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


## 6

In [9]:
import numpy as np

x = np.array([1, 4, 9, 16])
y = np.array([2, 1, 4, 5])

sqrt_x = np.sqrt(x)
print(sqrt_x)

result = np.maximum(sqrt_x, y)
print(result)

[1. 2. 3. 4.]
[2. 2. 4. 5.]


## 7

In [10]:
import numpy as np

arr = np.arange(24).reshape((2, 3, 4))
transposed_arr = arr.transpose((1, 0, 2))
print(transposed_arr.shape)

(3, 2, 4)


## 8

In [11]:
import numpy as np

arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
arr_con = np.array([True, False, True])

result = np.where(arr_con, arr_x, arr_y)
print(result)

[1 6 7]


## 9

In [12]:
import numpy as np

arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])

print(arr.mean())
print(np.sort(arr, axis=0))

3.888888888888889
[[3 2 2]
 [4 3 2]
 [6 6 7]]


## 10

In [13]:
import numpy as np

np.random.seed(10)
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)
result = np.dot(A, B)

print("矩阵A：")
print(A)
print("矩阵B：")
print(B)
print("矩阵A和B的点积：")
print(result)

矩阵A：
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]]
矩阵B：
[[0.49850701 0.22479665]
 [0.19806286 0.76053071]]
矩阵A和B的点积：
[[0.38861894 0.18917279]
 [0.46418833 0.71193035]]
